### ISSUE TITLE
Destroying crystal block SMP crash

### ISSUE THREAD

**Issue by spannerman79** [theflogat/Technomancy#180]
Forge 1614

Technomancy: [0.12.4](http://minecraft.curseforge.com/projects/technomancy/files/2277177)

Place down crystal block - used for water rutual - safe for decoration.

Break block (creative)

Crash (client)
````
java.lang.ArrayIndexOutOfBoundsException: 4
	at thaumcraft.common.blocks.BlockCosmeticOpaque.func_149691_a(BlockCosmeticOpaque.java:65)
	at net.minecraft.client.particle.EntityDiggingFX.<init>(EntityDiggingFX.java:26)
	at net.minecraft.client.particle.EntityDiggingFX.<init>(EntityDiggingFX.java:19)
	at net.minecraft.client.particle.EffectRenderer.func_147215_a(EffectRenderer.java:241)
	at net.minecraft.client.renderer.RenderGlobal.func_72706_a(RenderGlobal.java:3103)
	at net.minecraft.world.World.func_72889_a(World.java:3757)
	at net.minecraft.world.World.func_72926_e(World.java:3748)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78751_a(PlayerControllerMP.java:120)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78744_a(PlayerControllerMP.java:63)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78743_b(PlayerControllerMP.java:158)
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1409)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1948)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)
````

Message on server;

````
 NetworkDispatcher exception
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.8.0_72]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.8.0_72]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_72]
        at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_72]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:1.8.0_72]
        at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:436) ~[UnpooledUnsafeDirectByteBuf.class:?]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:870) ~[AbstractByteBuf.class:?]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:208) ~[NioSocketChannel.class:?]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:87) [AbstractNioByteChannel$NioByteUnsafe.class:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:480) [NioEventLoop.class:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447) [NioEventLoop.class:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341) [NioEventLoop.class:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [SingleThreadEventExecutor$2.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
````

**Comment by Mordenkainen** [comment]
Not sure what is going on here. The crash indicates  the problem was in one of Thaumcrafts classes, and the ritual crystals dont use thise classes at all! I'm not sure how this error could happen.

**Comment by Mordenkainen** [comment]
Closing this as it seems a non-issue.
