### ISSUE TITLE
fml log spam.

### ISSUE THREAD

**Issue by mkire** [theflogat/Technomancy#186]
I keep getting the following errors, to the point where multi-mc stops monitoring the logs, and i'm also finding 500MB+ log files after a few hours of play. If this isn't technomancy doing this, would you please help me figure out what is?

[02:12:23] [Client thread/ERROR]: Exception caught during firing event net.minecraftforge.client.event.RenderWorldLastEvent@4b96aca4:
java.lang.NoClassDefFoundError: theflogat/technomancy/common/items/thaumcraft/ItemTechnoturgeScepter
    at powercrystals.minefactoryreloaded.MineFactoryReloadedClient.renderWorldLast(MineFactoryReloadedClient.java:447) ~[MineFactoryReloadedClient.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_759_MineFactoryReloadedClient_renderWorldLast_RenderWorldLastEvent.invoke(.dynamic) ~[?:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
    at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:261) [ForgeHooksClient.class:?]
    at sun.reflect.GeneratedMethodAccessor52.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
    at Reflector.callVoid(Reflector.java:198) [Reflector.class:?]
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1709) [blt.class:?]
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1305) [blt.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
[02:12:23] [Client thread/ERROR]: Index: 1 Listeners:
[02:12:23] [Client thread/ERROR]: 0: HIGHEST
[02:12:23] [Client thread/ERROR]: 1: ASM: powercrystals.minefactoryreloaded.MineFactoryReloadedClient@18c7c858 renderWorldLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[02:12:23] [Client thread/ERROR]: 2: ASM: com.vanhal.progressiveautomation.events.EventRenderWorld@71321fa0 renderWorldLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[02:12:23] [Client thread/ERROR]: 3: NORMAL
[02:12:23] [Client thread/ERROR]: 4: ASM: fastcraft.d@38a469af a(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[02:12:23] [Client thread/ERROR]: 5: ASM: mcp.mobius.waila.overlay.DecoratorRenderer@64f6cd2f onRenderWorldLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[02:12:23] [Client thread/ERROR]: 6: ASM: vazkii.botania.common.item.ItemCraftingHalo@649fc168 onRenderWorldLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[02:12:23] [Client thread/ERROR]: 7: ASM: ivorius.reccomplex.events.RCForgeEventHandler@2458d849 onDrawWorld(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[02:12:23] [Client thread/ERROR]: 8: ASM: tombenpotter.sanguimancy.items.corrupted.ItemCorruptedShovel@4a15c1a5 drawTransmutationsAndBreakdowns(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[02:12:23] [Client thread/ERROR]: 9: ASM: codechicken.nei.ClientHandler@146e892d renderLastEvent(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[02:12:23] [Client thread/ERROR]: 10: ASM: cn.academy.core.client.util.CameraPosition@5077dd42 onRender(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[02:12:23] [Client thread/ERROR]: 11: ASM: WayofTime.alchemicalWizardry.client.renderer.RitualDivinerRender@2e026548 render(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[02:12:23] [Client thread/ERROR]: 12: ASM: blusunrize.immersiveengineering.client.ClientEventHandler@718bfd76 lastWorldRender(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[02:12:23] [Client thread/ERROR]: 13: ASM: mcp.mobius.waila.overlay.DecoratorRenderer@276e165e onRenderWorldLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[02:12:23] [Client thread/ERROR]: 14: ASM: vazkii.botania.client.core.handler.LightningHandler@797c4b43 onRenderWorldLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[02:12:23] [Client thread/ERROR]: 15: ASM: vazkii.botania.client.core.handler.BoundTileRenderer@1d9ee552 onWorldRenderLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[02:12:23] [Client thread/ERROR]: 16: ASM: vazkii.botania.client.core.handler.SubTileRadiusRenderHandler@8a077c5 onWorldRenderLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[02:12:23] [Client thread/ERROR]: 17: ASM: vazkii.botania.client.core.handler.MultiblockRenderHandler@273fb26 onWorldRenderLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[02:12:23] [Client thread/ERROR]: 18: ASM: vazkii.botania.client.render.world.SkyblockRenderEvents@4609a59 onRender(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[02:12:23] [Client thread/ERROR]: 19: ASM: crazypants.enderio.teleport.TravelController@6f839200 onRender(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[02:12:23] [Client thread/ERROR]: 20: ASM: matteroverdrive.client.RenderHandler@54f16acc onRenderWorldLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[02:12:23] [Client thread/ERROR]: 21: ASM: openblocks.client.SoundEventsManager@373d4913 renderEvents(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[02:12:23] [Client thread/ERROR]: 22: ASM: openblocks.client.model.ModelCraneBackpack@30f7d38b renderFppArm(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[02:12:23] [Client thread/ERROR]: 23: ASM: openblocks.client.renderer.entity.EntitySelectionHandler@2288e69d renderEvents(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[02:12:23] [Client thread/ERROR]: 24: ASM: mcjty.rftools.ClientProxy@744c703a renderWorldLastEvent(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[02:12:23] [Client thread/ERROR]: 25: ASM: journeymap.client.forge.event.WaypointBeaconHandler@3bedcc6e onRenderWorldLastEvent(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[02:12:23] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.reflect.InvocationTargetException
[02:12:23] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at sun.reflect.GeneratedMethodAccessor52.invoke(Unknown Source)
[02:12:23] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[02:12:23] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at java.lang.reflect.Method.invoke(Unknown Source)
[02:12:23] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at Reflector.callVoid(Reflector.java:198)
[02:12:23] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1709)
[02:12:23] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1305)
[02:12:23] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
[02:12:23] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
[02:12:23] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at net.minecraft.client.main.Main.main(SourceFile:148)
[02:12:23] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02:12:23] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[02:12:23] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[02:12:23] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at java.lang.reflect.Method.invoke(Unknown Source)
[02:12:23] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[02:12:23] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[02:12:23] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02:12:23] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[02:12:23] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[02:12:23] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at java.lang.reflect.Method.invoke(Unknown Source)
[02:12:23] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
[02:12:23] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
[02:12:23] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at org.multimc.EntryPoint.listen(EntryPoint.java:170)
[02:12:23] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at org.multimc.EntryPoint.main(EntryPoint.java:54)
[02:12:23] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.NoClassDefFoundError: theflogat/technomancy/common/items/thaumcraft/ItemTechnoturgeScepter
[02:12:23] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at powercrystals.minefactoryreloaded.MineFactoryReloadedClient.renderWorldLast(MineFactoryReloadedClient.java:447)
[02:12:23] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at cpw.mods.fml.common.eventhandler.ASMEventHandler_759_MineFactoryReloadedClient_renderWorldLast_RenderWorldLastEvent.invoke(.dynamic)
[02:12:23] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[02:12:23] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
[02:12:23] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:261)
[02:12:23] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   ... 23 more

**Comment by Mordenkainen** [comment]
Do you have Thaumcraft installed? Did you disable the Technomancy wands/scepter?

**Comment by mkire** [comment]
No thaumcraft installed, and i didn't think i would need to disable the wands/scepters, I'll try that next time i load the game.
Below is a full log from start-up to the first twenty or so seconds of being logged in. It reached 1.7 or so MB before i hit the quit button.
https://drive.google.com/open?id=0B171LYBBLzekRlRvSEU4emtFYWM

**Comment by Mordenkainen** [comment]
Well there is the problem.

Technomancy is at its core a Thaumcraft mod. Sometimes it misbehaves if Thaumcraft is not installed.

That said it should work and I will take a look at the issue and see if I can do anything about it.

**Comment by mkire** [comment]
problem went away by installing thaumcraft, will see if it returns if i remove thaumcraft later

**Comment by Mordenkainen** [comment]
It will. I'm looking to see if there is anything I can do to prevent the issue.
