### ISSUE TITLE
Crashing in 1.7.10 with MFR if thaumcraft not installed.

### ISSUE THREAD

**Issue by MindCaged** [theflogat/Technomancy#201]
Okay, I don't know if you even support 1.7.10 anymore(I started playing it again because there's still many mods that are exclusive to 1.7.10 like Legends mod, Dragon Block C, and OreSpawn.)

Anyway, I tried to install Technomancy with Botania installed, but not Thaumcraft or Blood Magic, but it was crashing with something to do with the Technoturge Scepter. I tried disabling all the items in the config and it still crashed, then I tried installing Thaumcraft and now it loads, but I'd prefer not to play with thaumcraft, I suppose if you're not supporting 1.7.10 anymore(understandable) I can just leave it installed and not use it, maybe go through the config and disable anything annoying that pops up.

```
java.lang.NoClassDefFoundError: theflogat/technomancy/common/items/thaumcraft/ItemTechnoturgeScepter
	at powercrystals.minefactoryreloaded.MineFactoryReloadedClient.renderWorldLast(MineFactoryReloadedClient.java:447)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_846_MineFactoryReloadedClient_renderWorldLast_RenderWorldLastEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:261)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1354)
	at JinRyuu.JBRA.JBRAEnRen.func_78471_a(JBRAEnRen.java:23)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
	at JinRyuu.JBRA.JBRAEnRen.func_78480_b(JBRAEnRen.java:62)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassNotFoundException: theflogat.technomancy.common.items.thaumcraft.ItemTechnoturgeScepter
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 26 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: thaumcraft.common.items.wands.ItemWandCasting
	at com.google.common.base.Throwables.propagate(Throwables.java:160)
	at cofh.asm.CoFHAccessTransformer.transform(CoFHAccessTransformer.java:94)
	at lumien.loadingprofiler.asm.WrappedTransformer.transform(WrappedTransformer.java:19)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 28 more
Caused by: java.lang.ClassNotFoundException: thaumcraft.common.items.wands.ItemWandCasting
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at cofh.asm.CoFHAccessTransformer.transform(CoFHAccessTransformer.java:90)
	... 31 more
```

**Comment by Mordenkainen** [comment]
Hmm. I guess this isn't surprising. Not sure I can do much to fix it though.

**Comment by Speiger** [comment]
@Mordenkainen you can fix that if you load the "modules" via Reflection instead of "importing" the classes into your compat loader.
You have a hard dependency on your "API"s that you are using.
